# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a09c32b0a38fe2ff44787f5976edbb67daedb465f19bef75b23548636fbe089429822f639a4cb451bc8ad904ac560377ffbabb1889c72d02bbc01e664eed13e

test:
  secret_key_base: c1aed131d0f165cc1a02cac7bf37e12c1ed00d34e7cadaad5d3a0c93f32075b3af51d562a508cfebd9c5e767386155a0be5d426e4411855ccc016b90365a8f21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
